# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Awesome OpenWrt - Wireless Freedom
description: Awesome-OpenWrt is a simple to setup and use OpenWrt for help when build or port.
baseurl:  # the subpath of your site, e.g. /support
url: https://awesome-openwrt.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Awesome OpenWrt #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Awesome OpenWrt
header: 玩转 OpenWrt
subheader: 构建属于自己的路由器系统
meta_image: odin-meta.png

# Social Links
# twitter_username: TheTeaGuns
# facebook_page:
# linkedin_page:
# instagram_username: 
# email: me@stuarthua.com
github_username: awesome-openwrt


# Navivation
# nav_item_one: Github
# nav_item_one_link: https://github.com/TeaGuns/odin

# nav_item_two: Twitter
# nav_item_two_link: https://twitter.com/TheTeaGuns

# nav_item_three: #
# nav_item_three_link: #

# nav_button: Return to Odin Home
# nav_button_link: https://teaguns.github.io/odin/

nav_button: Github
nav_button_link: https://github.com/awesome-openwrt

# More Help
help_one_title: 问题
help_one_content: 如有疑问，请前往 Github Issue 提问.
help_one_button: Github
help_one_link: https://github.com/awesome-openwrt

help_two_title: 群组
help_two_content: 与其他用户交流使用经验.
help_two_button: Telegram
help_two_link: https://github.com/awesome-openwrt

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
